"""empty message

Revision ID: 18dc1640c826
Revises: 
Create Date: 2021-03-16 00:38:21.964400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dc1640c826'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vet',
    sa.Column('idvet', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=100), nullable=True),
    sa.Column('whatsapp', sa.String(length=100), nullable=True),
    sa.Column('acceso', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idvet', name=op.f('pk_vet'))
    )
    op.create_table('uservet',
    sa.Column('iduservet', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('apellidos', sa.String(length=250), nullable=True),
    sa.Column('telefono', sa.String(length=250), nullable=True),
    sa.Column('tipo_uservet', sa.String(length=250), nullable=True),
    sa.Column('estado_uservet', sa.String(length=250), nullable=True),
    sa.Column('validado', sa.String(length=250), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.Column('vet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vet_id'], ['vet.idvet'], name=op.f('fk_uservet_vet_id_vet')),
    sa.PrimaryKeyConstraint('iduservet', name=op.f('pk_uservet')),
    sa.UniqueConstraint('dni', name=op.f('uq_uservet_dni')),
    sa.UniqueConstraint('email', name=op.f('uq_uservet_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uservet')
    op.drop_table('vet')
    # ### end Alembic commands ###
